# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  fearlesscities:
    - network.fearlesscities.com
    - fearless.localhost
  repository_url: https://github.com/Platoniq/decidim-bcnencomu
  alternative_assembly_types:
    - 
      key: organs # used to search a I18n key and a route path
      position_in_menu: 2.6
      assembly_type_ids: [17]
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  omniauth:
    facebook:
      # It must be a boolean. Remember ENV variables doesn't support booleans.
      enabled: false
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>
    twitter:
      enabled: false
      api_key: <%= ENV["OMNIAUTH_TWITTER_API_KEY"] %>
      api_secret: <%= ENV["OMNIAUTH_TWITTER_API_SECRET"] %>
    google_oauth2:
      enabled: false
      client_id: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_ID"] %>
      client_secret: <%= ENV["OMNIAUTH_GOOGLE_CLIENT_SECRET"] %>
    decidim:
      enabled: false
      client_id: <%= ENV["DECIDIM_CLIENT_ID"] %>
      client_secret: <%= ENV["DECIDIM_CLIENT_SECRET"] %>
      site_url: <%= ENV["DECIDIM_SITE_URL"] %>
      icon_path: media/images/icon-bcnencomu.png
    civicrm:
      enabled: false
      client_id: <%= ENV["CIVICRM_CLIENT_ID"] %>
      client_secret: <%= ENV["CIVICRM_CLIENT_SECRET"] %>
      site: <%= ENV["CIVICRM_SITE"] %>
      icon_path: media/images/icon-bcnencomu.png
  maps:
    api_key: <%= ENV["MAPS_API_KEY"] %>
  etherpad:
    server: <%= ENV["ETHERPAD_SERVER"] %>
    api_key: <%= ENV["ETHERPAD_API_KEY"] %>
    api_version: "1.2.1"
  videoconferences:
    jitsi:
      domain: <%= ENV["JITSI_DOMAIN"] %>
  civicrm:
    api:
      url: <%= ENV["CIVICRM_API_URL"] %>
      key: <%= ENV["CIVICRM_API_API_KEY"] %>
      secret: <%= ENV["CIVICRM_API_SECRET"] %>
development:
  <<: *default
  secret_key_base: 1642f6c3027b26d214056981fd147d52fe5f22e0f9e33a56196a22d6f642541d245bb8eb03eb5340aebffb72c0646cd87a6210ffcc6c5cc0d0a54b04c3892207
  omniauth:
    developer:
      enabled: true
      icon: phone
    civicrm:
      enabled: false
      client_id: <%= ENV["CIVICRM_CLIENT_ID"] %>
      client_secret: <%= ENV["CIVICRM_CLIENT_SECRET"] %>
      site: <%= ENV["CIVICRM_SITE"] %>
      icon_path: media/images/icon-bcnencomu.png
  civicrm:
    api:
      url: <%= ENV["CIVICRM_API_URL"] %>
      key: <%= ENV["CIVICRM_API_API_KEY"] %>
      secret: <%= ENV["CIVICRM_API_SECRET"] %>

test:
  <<: *default
  secret_key_base: 3ccf5fd4bbcba2b13468279fca37e311f89159ce73418dfec39d79e0b93fcab50da865a9de5303f76d43c3181fa15473e76375d42949635579d59b79abd38461
  omniauth:
    facebook:
      enabled: true
    twitter:
      enabled: true
    google_oauth2:
      enabled: true

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  alternative_assembly_types:
    - 
      key: organs # used to search a I18n key and a route path
      position_in_menu: 2.6
      assembly_type_ids: [18,19] # encomuparticipa & test.encomuparticipa
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_port: "587"
  smtp_starttls_auto: true
  smtp_authentication: "plain"
